# Compose v2 (no top-level version key needed)
services:
  web:
    # Prefer pulling the prebuilt image from GHCR (built by GitHub Actions)
    # Set GHCR_OWNER in .env; defaults to "itsfimall" if unset.
    image: ghcr.io/${GHCR_OWNER:-lynn3t}/fim-ai-chat:latest
    # To build locally from source instead, comment the line above and uncomment below:
    # build: .
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NEXT_TELEMETRY_DISABLED=1
      - AUTO_SEED=true
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fimai
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
