name: Build and Deploy Docker Image

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Convert repository name to lowercase
      id: repo_name
      run: echo "REPO_NAME_LOWER=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
      
    - name: Login to Container Registry
      if: github.event_name == 'push'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: ${{ github.event_name == 'push' }}
        tags: |
          ghcr.io/${{ steps.repo_name.outputs.REPO_NAME_LOWER }}:latest
          ghcr.io/${{ steps.repo_name.outputs.REPO_NAME_LOWER }}:${{ github.sha }}
        build-args: |
          JWT_SECRET=${{ secrets.JWT_SECRET || 'build-secret-only' }}
        cache-from: type=gha
        cache-to: type=gha,mode=max